#
#  makefile - RPN (Reverse Polish) calculator simulator.
#
#  Copyright(C) 2024 - macmpi
#
#  makefile for BSD variants systems (NetBSD & Darwin)
#
#  This  program is free software: you can redistribute it and/or modify it
#  under  the terms of the GNU General Public License as published  by  the
#  Free  Software Foundation, either version 3 of the License, or (at  your
#  option) any later version.
#
#  This  program  is distributed in the hope that it will  be  useful,  but
#  WITHOUT   ANY   WARRANTY;   without even   the   implied   warranty   of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
#  Public License for more details.
#
#  You  should have received a copy of the GNU General Public License along
#  with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#  Note seperator (tab) at the beginning of the line CANNOT be a space..!
#
#  https://stackoverflow.com/questions/50941196/
#
#  https://www.gnu.org/software/make/manual/html_node/Prerequisite-Types.html
#
#  28 Mar 24         - Initial version - macmpi
#  06 May 24			- Fixed include path for Darwin - MT
#  12 May 24         - Use a separate makefile for MacOS - MT
#

CFLAGS	?=
LDFLAGS	?=
LDLIBS	?=

OS != uname -s

# Operating system specific settings
.if ${OS} == "FreeBSD"
LANG 	= LANG_en
LDLIBS	+= -lcompat
CFLAGS	+= -Wno-variadic-macros
CFLAGS	+= -I/usr/local/include/
LDFLAGS	+= -L/usr/local/lib/
.endif

.if ${OS} == "NetBSD"
LANG 	= LANG_en
LDLIBS	+= -lcompat
CFLAGS	+= -Wno-variadic-macros
CFLAGS	+= -I/usr/X11R7/include/
LDFLAGS	+= -L/usr/X11R7/lib/ -R /usr/X11R7/lib
.endif

include makefile.all
